### ISSUE TITLE
Cryptokey is not defined

### ISSUE THREAD

**Issue by Aleksi1212** [finsweet/fireworkers#12]
I'm using this with these values:
const db = await Firestore.init({
    uid: nanoid(16),
    project_id: serviceAccount.project_id,
    client_email: serviceAccount.client_email,
    private_key: serviceAccount.private_key,
    private_key_id: serviceAccount.private_key_id,
    claims: {
        premium_account: true
    }
});

and if i try to create document. I get ReferenceError: CryptoKey is not defined in node_modules/dist/index.js.

**Comment by maxprilutskiy** [comment]
@Aleksi1212 it's likely because of `nanoid`
