### ISSUE TITLE
Incorrect Endpoint URL in v0.2.0

### ISSUE THREAD

**Issue by aliyome** [finsweet/fireworkers#16]
## Description
I've noticed a discrepancy in the endpoint URL between version v0.1.0 and v0.2.0. The URL structure seems to have changed, leading to potential issues.

## Details
In v0.1.0, the endpoint was: https://firestore.googleapis.com/v1/projects/{project_id}/databases/(default)/documents/{path}
In v0.2.0, it has changed to: https://firestore.googleapis.com/v1/projects/{project_id}/databases/(default)/{path}

## Expected Behavior
The endpoint URL should remain consistent across versions, or a change should be clearly documented.

## Actual Behavior
The endpoint URL has changed between v0.1.0 and v0.2.0 without clear documentation.

## Steps to Reproduce
- Use the endpoint in v0.1.0 via `get` method.
- Update to v0.2.0, and use `get` method.
- Observe the change in the endpoint URL.

**Comment by alexiglesias93** [comment]
Should be fixed in `v.0.2.1`, thank you for reporting!
